#!/sbin/busybox sh

echo $0 $* >> /dev/null

if [ -f /sbin/recovery-is-running ];
then
    if (echo "$*" | grep -q -i "/datadata") || (echo "$*" | grep -q -i "/dbdata"); then
        /sbin/busybox umount /datadata >> /dev/null 2>&1
        echo /sbin/busybox umount /datadata >> /dev/null
        /sbin/busybox umount /dbdata >> /dev/null 2>&1
        echo /sbin/busybox umount /dbdata >> /dev/null
    else
	/sbin/busybox umount $*
	echo /sbin/busybox umount $* >> /dev/null
    fi;
else
    /sbin/busybox umount $*
    echo /sbin/busybox umount $* >> /dev/null
fi;
